### ISSUE TITLE
module error in VS Code

### ISSUE THREAD

**Issue by smout74** [jakearchibald/idb#95] opened 2019-03-20 10:39 UTC
Hi,

I get this error in Visual Studio Code when compiling during testing with an Ionic 4 app (with Angular)
The database and entry are created fine though.
idb version 4.0.0

`[ng] ERROR in node_modules/idb/build/esm/entry.d.ts(375,13): error TS2339: Property 'asyncIterator' does not exist on type 'SymbolConstructor'.
[ng] node_modules/idb/build/esm/entry.d.ts(375,31): error TS2304: Cannot find name 'AsyncIterableIterator'.
[ng] node_modules/idb/build/esm/entry.d.ts(382,98): error TS2304: Cannot find name 'AsyncIterableIterator'.
[ng] node_modules/idb/build/esm/entry.d.ts(441,13): error TS2339: Property 'asyncIterator' does not exist on type 'SymbolConstructor'.
[ng] node_modules/idb/build/esm/entry.d.ts(441,31): error TS2304: Cannot find name 'AsyncIterableIterator'.
[ng] node_modules/idb/build/esm/entry.d.ts(450,109): error TS2304: Cannot find name 'AsyncIterableIterator'.
[ng] node_modules/idb/build/esm/entry.d.ts(502,13): error TS2339: Property 'asyncIterator' does not exist on type 'SymbolConstructor'.
[ng] node_modules/idb/build/esm/entry.d.ts(502,31): error TS2304: Cannot find name 'AsyncIterableIterator'.
[ng] node_modules/idb/build/esm/entry.d.ts(534,13): error TS2339: Property 'asyncIterator' does not exist on type 'SymbolConstructor'.
[ng] node_modules/idb/build/esm/entry.d.ts(534,31): error TS2304: Cannot find name 'AsyncIterableIterator'.`

`import { Component } from '@angular/core';
import { openDB } from 'idb';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {

  constructor(){
    this.createDB();
  }

  async createDB() {
    const db = await openDB('IDBtest', 1, {
      upgrade(db) {
            console.log('making a new object store');
            db.createObjectStore('testsettings', { autoIncrement: true });
          } 
    });
    await db.put('testsettings', { server: '127.0.0.1' }, 1);  
  }
}`

**Comment by smout74** [comment] 2019-03-20 11:04
Too fast, sorry, idb/with-async-ittr.js solves this error.

Thanks for this awesome wrapper

**Comment by jakearchibald** [comment] 2019-03-20 11:24
Were you using async iterators at all? If not, I'm kinda surprised you got this error

**Comment by smout74** [comment] 2019-03-20 11:34
Just executed the code above (in a new project), nothing more.

But with `import { openDB } from 'idb/with-async-ittr.js';
` the error is gone.

**Comment by jakearchibald** [comment] 2019-03-20 11:40
I'm going to leave this open to investigate

**Comment by smout74** [comment] 2019-03-20 12:39
I will send you the full code

**Comment by jakearchibald** [comment] 2019-03-20 13:17
Thanks! Anything that makes it easier to reproduce the problem locally will be really useful.

**Comment by smout74** [comment] 2019-03-20 14:39
you should have received a github repo invitation, there you can find the code

**Comment by shreeshbhat** [comment] 2019-03-24 04:42
Seeing the same error in my project as well.
Importing with 'idb/with-async-ittr.js' instead of 'idb' resolved the vscode error.

Code : 
`import { openDB } from 'idb/with-async-ittr.js';

export async function openDb() {
  const db = await openDB('Todos', 1, {
    upgrade(db) {
      const store = db.createObjectStore('todos', {
        keyPath: 'id',
        autoIncrement: true,
      });
      store.createIndex('tags', 'tags');
    },
  });
  return db;
}

export async function setTodos(todos: any) {
  const db = await openDb();
  await db.add('todos', todos[todos.length]);
}

export async function getTodos() {
  const db = await openDb();
  return await db.getAll('todos');
}
`

**Comment by jakearchibald** [comment] 2019-03-24 06:23
If your project also ionic?

**Comment by shreeshbhat** [comment] 2019-03-24 14:55
I am using stenciljs starter project, web component compiler used by Ionic.
The issue might be the way stencil does rollup then.
They did have some issue in their latest version, so I m using one version lower.
You can have a look at my project at https://github.com/shreeshbhat/strike-off 
Thanks for responding quickly! :)

**Comment by shreeshbhat** [comment] 2019-03-24 15:16
Also, how do I import types for idb?
Sorry, I am new to typescript. 
Trying npm install @types/idb didn't help.
When enabling strict mode in typescript, getting the following error : 
```Could not find a declaration file for module 'idb/with-async-ittr.js'. 
'/node_modules/idb/with-async-ittr.js' implicitly has an 'any' type.
Try `npm install @types/idb` if it exists or add a new declaration (.d.ts) file
containing `declare module 'idb/with-async-ittr.js';```

**Comment by sgabb** [comment] 2019-04-09 15:11
Hi, maybe the problem depends on the configuration of tsconfig.json and/or the import of the node_modules/@types...
I have an Angular project with this tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "allowSyntheticDefaultImports": true,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "importHelpers": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}
```
In the **idb/build/esm/entry.d.ts** file I get the errors "Property 'asyncIterator' does not exist on type 'SymbolConstructor'." and "Cannot find name 'AsyncIterableIterator'." probably because it is not finding the correct file where the definitions are.
It searches in the _**...\node_modules\typescript\lib\lib.es2015.iterable.d.ts**_ file, while the **idm/lib/entry.ts** file correctly search the interfaces in _**...\node_modules\typescript\lib\lib.esnext.asynciterable.d.ts**_

How is the correct way to set things in order to work?

**Comment by Hagbards** [comment] 2019-05-10 15:25
Hi, first of all thanks for this project.
Unfortunately i got the 
`ERROR in node_modules/idb/build/esm/entry.d.ts(375,13): error TS2339: Property 'asyncIterator' does not exist on type 'SymbolConstructor'.` error.

I have just created a service.

import { Injectable } from '@angular/core';
import {openDB} from 'idb';

`@Injectable({
  providedIn: 'root'
})
export class IdbService {

  constructor() { }
}`

**Comment by jcharlesworthuk** [comment] 2019-05-15 13:13
I am also getting this error after updating to version 4, I'm not using angular though, my code looks like this

```
import { openDB } from 'idb';
const database = await openDB('mydb', 2, {
        upgrade(db, oldVersion , newVersion, transaction) {
        }
   });
```

Errors from webpack are:

ERROR in [at-loader] ./node_modules/idb/build/esm/entry.d.ts:375:13 
    TS2339: Property 'asyncIterator' does not exist on type 'SymbolConstructor'.
ERROR in [at-loader] ./node_modules/idb/build/esm/entry.d.ts:375:31 
    TS2304: Cannot find name 'AsyncIterableIterator'.

This worked fine with version 3 of idb

**Comment by Jack-Works** [comment] 2019-05-31 06:37
Yes, there is a type definition for 'idb' but not with 'idb/with-async-ittr'.

I have to write a file to solve this.

```ts
declare module 'idb/with-async-ittr' {
    export * from 'idb'
}
```

**Comment by kushtrimjunuzi** [comment] 2019-06-13 19:46
I'm using angular2 (v2.4.10), typescript (2.2.2) and getting lots of errors.
Trying to use idb (v4.0.3)

My tsconfig.json
```
{
	"compilerOptions": {
		"baseUrl": "",
		"declaration": false,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"lib": ["es6", "dom"],
		"mapRoot": "./",
		"module": "es6",
		"moduleResolution": "node",
		"outDir": "../dist/out-tsc",
		"sourceMap": true,
		"target": "es5",
		"typeRoots": [
			"../node_modules/@types"
		]
	},
	"exclude": ["node_modules"],
	"angularCompilerOptions": {
		"preserveWhiteSpace": false
	}
}
```

and imported as:
```
import { openDB } from 'idb';
```

Some of the errors when running ```$ng serve```:
```
ERROR in ./node_modules/idb/build/esm/entry.d.ts (526,328): Cannot find name 'IndexName'.
ERROR in ./node_modules/idb/build/esm/entry.d.ts (530,21): 'StoreValue' only refers to a type, but is being used as a value here.
ERROR in ./node_modules/idb/build/esm/entry.d.ts (534,13): Property 'asyncIterator' does not exist on type 'SymbolConstructor'.
ERROR in ./node_modules/idb/build/esm/entry.d.ts (534,31): Cannot find name 'AsyncIterableIterator'.
ERROR in ./node_modules/idb/build/esm/entry.d.ts (536,1): Cannot find name 'declare'.
ERROR in ./node_modules/idb/build/esm/entry.d.ts (536,9): Cannot find name 'type'.
ERROR in ./node_modules/idb/build/esm/entry.d.ts (536,14): Cannot find name 'IDBPCursorWithValueIteratorValueExtends'.
ERROR in ./node_modules/idb/build/esm/entry.d.ts (536,54): Cannot find name 'DBTypes'.

```

**Comment by lrxw** [comment] 2019-07-15 09:39
I get the same error with Angular 7 and idb 4.0.4

**Comment by josduj** [comment] 2019-07-16 13:05
Adding `esnext.asynciterable` to tsconfig worked for me.

```json
{
    "compilerOptions": {
        "lib": [
            "esnext.asynciterable",
            "es2018",
            "dom"
        ],
        ...
    },
    ...
}

**Comment by NotWoods** [comment] 2019-10-13 23:55
It's possible that the library depends on the `esnext.asynciterable` lib but some user's don't have that lib (probably because their target is lower). A possible fix is adding a [triple-slash directive](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) to the `with-async-ittr.js` file:

```ts
/// <reference lib="es2018.asynciterable" />
```

**Comment by jakearchibald** [comment] 2020-01-09 17:31
I'm going to close this, but if anyone can create a project that minimally reproduces the error, please reopen and I'll take a look.

**Closed by jakearchibald** 2020-01-09 17:31 UTC

**Comment by jakearchibald** [comment] 2020-01-29 13:40
Fwiw, I'm pretty sure these error are down to:

* Using an old version of TypeScript/Angular.
* Missing "esnext" in the libs section of `tsconfig.json`.
