### ISSUE TITLE
openDB get stucked forever in blocked state in Safari iOS

### ISSUE THREAD

**Issue by planeth44** [jakearchibald/idb#139] opened 2019-11-07 09:07 UTC
My app works as a PWA but is not “installed” as one (no manifest). However I don't think it's relevant to this particular problem.
This is how it goes : the user access the page, the indexedDB is created. User uses the app.
Then the user decides to no longer authorize ccokies. (Go to settings and disable cookie)
Now the app is no longer working, so said user goes back to allow cookies again.

This is when the problem arise: openDB is stuck in ‘blocked‘ state forever.
You can close all the windows you want. Close Safari. Nothing will do unless the user goes to setting and ask for ‘delete the site data’. Which means the DB is deleted.

Tested with Safari iOS 13.
Is there a way to get unstuck without resorting to drastic erase of the DB ?
Thanks for any insight

BTW, thanks for this awesome library :)

**Comment by jakearchibald** [comment] 2020-01-09 16:58
Can you create an example of this issue on something like glitch.com? However, it sounds like this is a bug with Safari, and not with this library.

**Comment by YudiTjhia** [comment] 2020-04-27 09:04
please help ...
![image](https://user-images.githubusercontent.com/2868481/80354309-be798000-88a0-11ea-9e4e-d6173d623a90.png)


![image](https://user-images.githubusercontent.com/2868481/80354345-cf29f600-88a0-11ea-8b95-461730bf43b1.png)

**Comment by jakearchibald** [comment] 2020-04-27 10:10
That looks like an old version of the library, and I'd need more than a screenshot to help debug it.

I'm closing this issue since there's no minimal reproduction.

**Closed by jakearchibald** 2020-04-27 10:10 UTC

**Comment by YudiTjhia** [comment] 2020-04-27 11:09
[image: image.png]

[image: image.png]

Best Regards,
Yudi
+6281219972047
yudi.tjhia.85@gmail.com

**Comment by YudiTjhia** [comment] 2020-04-27 11:11
![image](https://user-images.githubusercontent.com/2868481/80365836-6cd9f100-88b2-11ea-905e-4b987c8a8baa.png)

![image](https://user-images.githubusercontent.com/2868481/80365917-8f6c0a00-88b2-11ea-90f0-2e2df591f328.png)

**Comment by jakearchibald** [comment] 2020-04-27 11:30
Hi, it's impossible to debug something like this with just screenshots. However, if this is a firebase issue, please raise it with them.

**Comment by planeth44** [comment] 2020-04-27 11:56
Sorry @jakearchibald I didn't find the time to build a glitch app. I discussed the matter with Maximiliano Firtman and he said it was probably a Safari iOS bug. I filed an issue in the bugtracker. No news since then.
